### PR TITLE
Split aws_account resource into aws_account and aws_organization

### PR DESCRIPTION
**Pull request by rlenglet**
Update the aws_account resource to only support non-org-management accounts.
Remove unnecessary attributes: account_type and management_account_id.
Rename organization_id attribute into organization_master_account_id and change its semantics, because the backend correlates accounts using the org's management/master account ID instead of the organization ID.

Fix the modes of aws_account attributes.
Replace incorrect usages of WriteOnlyOnceAttributeMode with ImmutableAttributeMode.
Add the missing RequiresReplace plan modifier to each ImmutableAttributeMode attribute.

Reorder attributes by lexicographic order in the schema.

Define a new aws_organization resource specific to org accounts.

Update resource examples.

### CODE REVIEW

**Comment by rlenglet** [comment]
@itsesterline could you please double-check that the documentation is OK?

**Comment by shireesh-illumio** [comment]
needs correction to the fields

```go
// Copyright (c) Illumio, Inc.
// SPDX-License-Identifier: MPL-2.0

package schema

import (
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	resource_schema "github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

var (
	awsAccountResource = Resource{
		TypeName: "aws_account",
		Schema: resource_schema.Schema{
			Version:     1,
			Description: "Manages an AWS account in CloudSecure.",
			Attributes: map[string]resource_schema.Attribute{
				IDFieldName: idAttribute,
				"name": resource_schema.StringAttribute{
					Description: "Display name.",
					Required:    true,
				},
				"account_id": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						MarkdownDescription: "AWS account ID.",
						Required:            true,
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
				"account_type": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						MarkdownDescription: "AWS account type, must be `\"Account\"` or `\"Organization\"`.",
						Required:            true,
						Validators: []validator.String{
							stringvalidator.OneOf("Account", "Organization"),
						},
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
				"mode": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description: "Access mode, must be `\"ReadWrite\"` (default) or `\"Read\"`.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("ReadWrite"),
						Validators: []validator.String{
							stringvalidator.OneOf("ReadWrite", "Read"),
						},
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
				"role_external_id": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description: "External ID defined in the AWS role to authenticate CloudSecure when assuming that role.",
						Required:    true,
					},
					attributeWithMode: attributeWithMode{
						Mode: WriteOnlyOnceAttributeMode,
					},
				},
				"role_arn": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description: "ARN of the AWS role to be assumed by CloudSecure to manage this account.",
						Required:    true,
					},
					attributeWithMode: attributeWithMode{
						Mode: WriteOnlyOnceAttributeMode,
					},
				},
				"organization_id": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description: "AWS organization ID. Required if `account_type` is `\"Organization\"`.",
						Optional:    true,
					},
					attributeWithMode: attributeWithMode{
						Mode: ImmutableAttributeMode,
					},
				},
			},
		},
	}

	awsOrganizationResource = Resource{
		TypeName: "aws_organization",
		Schema: resource_schema.Schema{
			Version:     1,
			Description: "Manages an AWS organization in CloudSecure.",
			Attributes: map[string]resource_schema.Attribute{
				IDFieldName: idAttribute,
				"name": resource_schema.StringAttribute{
					Description: "Display name.",
					Required:    true,
				},
				"management_account_id": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						MarkdownDescription: "AWS organization management account ID. If specified, `organization_id` must also be specified. Required if `account_type` is `\"Organization\"`.",
						Optional:            true,
					},
					attributeWithMode: attributeWithMode{
						Mode: WriteOnlyOnceAttributeMode,
					},
				},
				"organization_id": StringResourceAttributeWithMode{
					StringAttribute: resource_schema.StringAttribute{
						Description: "AWS organization ID. If specified, the whole AWS organization is onboarded instead of just the AWS account. If specified, `management_account_id` must also be specified. Required if `account_type` is `\"Organization\"`.",
						Optional:    true,
					},
					attributeWithMode: attributeWithMode{
						Mode: WriteOnlyOnceAttributeMode,
					},
				},
			},
		},
	}
)

```

also need data resource of the organization.

**Comment by rlenglet** [comment]
> also need data resource of the organization.

No, that is not required. Users can get that org's management/master account ID using the `aws` Terraform provider's resources.
```
data "aws_organizations_organization" "example" {}

resource "illumio-cloudsecure_aws_account" "example" {
  # ...
  organization_account_id = data.aws_organizations_organization.example.master_account_id
  # ...
}
```

Cf. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/organizations_organization#master_account_id

**Comment by rlenglet** [comment]
@shireesh-illumio 

> needs correction to the fields

From your code snippet, I can infer that you recommend:

1. Re-adding the `account_type` attribute. Why? Removing this is one the main points of this PR.
2. Reverting the change to replace `organization_id ` with `organization_account_id`. That change is necessary, because the API backend requires the org's management/master account ID to correlate with the `aws_organization`. The organization ID is not used for joining in the backend. I clarified that point in this PR's description. Please re-read and confirm that this is clear to you.
3. Remove the `mode` attribute from the `aws_organization` resource. Why? This is necessary. Org management accounts are handled just like normal accounts in the backend.
4. Remove the `role_arn` and `role_external_id` from the `aws_organization` resource. Why? Those are absolutely required to onboard the org's management account. Org management accounts are handled just like normal accounts in the backend: they resources are ingested into inventory, rules are programmed into their security groups, etc.
5. Rename `account_id` into `management_account_id` in the `aws_organization` resource. OK, I'll do that.

So in the end, I'll only rename `account_id` into `management_account_id` in the `aws_organization` resource.

Next time, please clarify explicitly each change you would like to make in proper comments on the code, and why you think those changes are necessary.

**Comment by shireesh-illumio** [comment]
@rlenglet 

this is what i am proposing.

```tf
provider "aws"{
  
}
provider "aws" {
  alias   = "account1"
  profile = "account1"
  region  = "us-west-2"
}

data "aws_organizations_organization" "current" {}

data "aws_partition" "current" {}

data "aws_caller_identity" "current" {}

resource "illumio-cloudsecure_aws_org" "my_aws_org" {
  name = "My AWS"
  organization_id    = data.aws_organizations_organization.current.id
  management_account_id = data.aws_organizations_organization.current.master_account_id
}


module "aws_root_org" {
  source        = "shireesh-illumio/illumio-cloudsecure-integration/aws//modules/aws-account"
  version       = "0.0.9"
  iam_role_name = "IllumioCloudIntegrationRole"
  mode          = "ReadWrite"
  account_type  = "Organization"
  account_name  = "My AWS Organization"
  organization_id    = data.aws_organizations_organization.current.id
}

module "aws_child_org_1" {
  source        = "shireesh-illumio/illumio-cloudsecure-integration/aws//modules/aws-account"
  version       = "0.0.9"
  iam_role_name = "IllumioCloudIntegrationRole"
  mode          = "ReadWrite"
  account_type  = "Organization"
  account_name  = "My AWS Organization"
  organization_id    = data.aws_organizations_organization.current.id
  providers = {
    aws                 = aws.account1
    illumio-cloudsecure = illumio-cloudsecure
  }
}
```

**Comment by rlenglet** [comment]
@shireesh-illumio, why are you bringing up the Terraform modules? It's relevant for this PR.

**Comment by rlenglet** [comment]
@shireesh-illumio 
Re: https://github.com/illumio/terraform-provider-illumio-cloudsecure/pull/52#issuecomment-2289557255
Why are you ignoring the comments I made about this at https://github.com/illumio/terraform-provider-illumio-cloudsecure/pull/52#issuecomment-2289557255

**Comment by shireesh-illumio** [comment]
you are getting wrong notion of org.
org is not single intergration. org is parent and the children are the accounts.
we need n blocks of accounts for n accounts in a single org. 

the need for the org comes to have the org record have a name to show in the ui
else it wont serve any purpose as the org details can be added in account creation.

right now we can name accounts with names like stage,dev etc but org we dont have a place.

if we add org name to account we will have to duplicate the name in multiple account blocks.

**Comment by rlenglet** [comment]
> you are getting wrong notion of org.
> org is not single intergration. org is parent and the children are the accounts including the managment account.
> we need n blocks of accounts for n accounts in a single org.

That is incorrect. As we had previously discussed and documented, a CloudSecure AWS account of type "Organization" does onboard the management account ID (the "account_id" in the API) just like any other account of type "Account": its resources are ingested into inventory, flows are ingested, rules are programmed into security groups, etc. Therefore, both resources (of type "Organization" and "Account") require an account ID, a role ARN, and a role external ID.

**Comment by rlenglet** [comment]
@itsesterline I've improved the description/docs to clarify that an `aws_organization` manages both an AWS organization and that organization's master account. Please check that this makes sense.

**Review by itsesterline — APPROVED** [review]

**Pull request merged**
