### PR TITLE
Preserve the tags of Protocol Buffer message fields when adding new fields

### PR DESCRIPTION
**Pull request by rlenglet**
When adding or removing attributes in a Terraform resource's schema, the tags of the Protocol Buffer message fields corresponding to other resource attributes may get different tags when regenerating the .proto file. This breaks backward compatibility, which should not be the case when only adding an optional attribute.

Modify the protobuf generator implementation to preserve tags for existing attributes across resource schema modifications.

Assigned tags are now saved in a JSON file at `api/illumio/cloud/config/v1/tags.json`.
Any changes to this file must now be committed along with `api/illumio/cloud/config/v1/config.proto`.

### CODE REVIEW

**Comment by shireesh-illumio** [comment]
@rlenglet should we not throw error if the item is not present in the json. rather than auto adding the attributes to the json.

what happens if the type changed and not the name? 
i guess we will need to change name as well. add guidelines for this. somewhere.

**Review by shireesh-illumio — DISMISSED** [review]
lgtm

**Comment by rlenglet** [comment]
> what happens if the type changed and not the name?

That makes the API non-backward compatible, and that requires bumping the API version.
And in this case, the tags assigned in the previous version don't matter, because we start tagging from scratch.
I added that in the comment on `Version()` as another case of non-backward compatible change.

**Comment by shireesh-illumio** [comment]
so, should we remove the json file contents for that particular resource and generate if the version increments.

**Review by shireesh-illumio — APPROVED** [review]
lgtm

**Comment by rlenglet** [comment]
> so, should we remove the json file contents for that particular resource and generate if the version increments.

It's even more radical than that. Increasing the version implies changing the package name from e.g. v1 to v2, which means creating a new `api/illumio/cloud/config/v2/` directory and creating a new `config.proto` in there. A new `tags.json` will be created in that new directory on the first `go generate` execution.

**Pull request merged**
